services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db


  app:
    container_name: teamable_demo_app
    build:
      context: . 
      dockerfile: Dockerfile # Specifies the Dockerfile to use
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - .:/app # Mount the current directory to /app in the container
    environment:
      PORT: "3000"
      MONGO_URL: "mongodb://mongodb:27017"
      DB_NAME: "teamable_demo"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


volumes:
  mongo-data:
    

